{"uuid": "371d51ff-e049-4c36-ae71-0623deb3fe90", "children": ["4591892e-fef9-40bb-b611-95a9ad42bc35"], "befores": [{"name": "setup_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: Requested environment is not available\n\n", "trace": "  File \"/Users/maksimdenisenkov/qa_guru_python_9_jenkins/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/maksimdenisenkov/qa_guru_python_9_jenkins/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/Users/maksimdenisenkov/qa_guru_python_9_jenkins/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/maksimdenisenkov/qa_guru_python_9_jenkins/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/maksimdenisenkov/qa_guru_python_9_jenkins/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/maksimdenisenkov/qa_guru_python_9_jenkins/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/maksimdenisenkov/qa_guru_python_9_jenkins/conftest.py\", line 22, in setup_browser\n    driver = webdriver.Remote(\n        command_executor=f\"https://user1:1234@selenoid.autotests.cloud/wd/hub\",\n        options=options\n    )\n  File \"/Users/maksimdenisenkov/qa_guru_python_9_jenkins/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 275, in __init__\n    self.start_session(capabilities, browser_profile)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maksimdenisenkov/qa_guru_python_9_jenkins/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 365, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/Users/maksimdenisenkov/qa_guru_python_9_jenkins/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/Users/maksimdenisenkov/qa_guru_python_9_jenkins/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1749757177015, "stop": 1749757177218}], "start": 1749757177015, "stop": 1749757177279}